services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: chat_server
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: server_admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/chat_server
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: server_admin
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_DB_SCHEMA: keycloak
    command:
      - start-dev
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  pgdata: